app/suiviprojets/suiviprojets/urls.py
from django.contrib import admin
from django.urls import path
from suiviprojets.dashboard import views
from django.conf import settings

urlpatterns = [
    path(r'',views.index),
    path(r'projet/<str:id>/',views.details_projet),
    path(r'projets/',views.projets),
    path(r'projets/page/',views.projets_page),
    path(r'projets/sort/',views.projets_sort),
    path(r'projets/nb/',views.projets_nb),
    path(r'client/<str:id>/',views.details_client),
    path(r'clients/',views.clients),
    path(r'clients/page/',views.clients_page),
    path(r'clients/sort/',views.clients_sort),
    path(r'clients/nb/',views.clients_nb),
    path(r'currents/',views.currents),
    path('admin/', admin.site.urls),
    path(r'download/',views.download),
    path(r'kanban/search',views.accueil_search),
    #path(r'nom_domaines/',views.noms_domaines),
    path(r'travail/',views.temps_passe),
    path(r'projets/search/',views.projets_search),
    path(r'clients/search/',views.clients_search),
    #path(r'accueil/search/',views.accueil_search),
    path(r'add/',views.add),
    path(r'edit/',views.edit),
    path(r'save/',views.save),
    path(r'show/<str:id>/',views.tache_show),
]

app/suiviprojets/suiviprojets/dashboard/models.py
from django.db import models
import datetime


# Create your models here.

class TypePrestation(models.Model):
    id=models.AutoField(primary_key=True)
    type_prestation=models.CharField(max_length=100)
    notes=models.TextField(null=True,blank=True)
    
    def __str__(self):
        return self.type_prestation

class Flux(models.Model):
    id=models.AutoField(primary_key=True)
    flux=models.CharField(max_length=50)
    
    def __str__(self):
        return self.flux

class CategorieForfait(models.Model):
    id=models.AutoField(primary_key=True)
    categorie_forfait=models.CharField(max_length=100)
    duree=models.IntegerField(null=True,blank=True)
    flux=models.ForeignKey(Flux,on_delete=models.SET_NULL,null=True,blank=True)
    volume=models.DecimalField(decimal_places=1,max_digits=6,null=True,blank=True)

    def __str__(self):
        return self.categorie_forfait

class Revendeur(models.Model):
	id=models.AutoField(primary_key=True)
	nom=models.CharField(max_length=100)
	notes=models.TextField(null=True,blank=True)
	
	def __str__(self):
		return self.nom

class Client(models.Model):
    id=models.AutoField(primary_key=True)
    nom=models.CharField(max_length=125)
    adresse1=models.TextField(null=True,blank=True)
    adresse2=models.TextField(null=True,blank=True)
    code_postal=models.CharField(max_length=10,null=True,blank=True)
    ville=models.CharField(max_length=50,null=True,blank=True)
    

    def __str__(self):
        return self.nom  

class TypeProjet(models.Model):
	id=models.AutoField(primary_key=True)
	type_projet=models.CharField(max_length=25)
	icone=models.CharField(max_length=2500,null=True,blank=True)
	
	def __str__(self):
		return self.type_projet

class Projet(models.Model):
    id=models.AutoField(primary_key=True)
    date_creation=models.DateField(null=True,blank=True)
    date_fin_programmee=models.DateField(null=True,blank=True)
    client=models.ForeignKey(Client,on_delete=models.SET_NULL,null=True,blank=True)
    type_projet=models.ForeignKey(TypeProjet,on_delete=models.SET_NULL,null=True,blank=True)
    num_armoire=models.CharField(max_length=125,null=True,blank=True)
    revendeur=models.ForeignKey(Revendeur,on_delete=models.SET_NULL, null=True,blank=True)
    def __str__(self):
        return str(self.client)+"-"+str(self.type_projet)
    
class Forfait(models.Model):
    id=models.AutoField(primary_key=True)
    date_commande=models.DateField()
    projet= models.ForeignKey(Projet,on_delete=models.SET_NULL,null=True,blank=True)
    url=models.CharField(max_length=50,null=True,blank=True)
    classeurs=models.CharField(max_length=150,null=True,blank=True)
    categorie_forfait= models.ForeignKey(CategorieForfait,on_delete=models.SET_NULL,null=True,blank=True)
    def __str__(self):
        return self.projet.client.nom+"-"+self.categorie_forfait.categorie_forfait
              


class Consommation(models.Model):
    id=models.AutoField(primary_key=True)
    date=models.DateField(auto_now_add=True)
    forfait=models.ForeignKey(Forfait,on_delete=models.SET_NULL,null=True,blank=True)
    nb_docs=models.IntegerField(null=True,blank=True)
    volume_docs=models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True)
    
    def __str__(self):
        return self.forfait.categorie_forfait.categorie_forfait+"Nb de documents::"+str(self.nb_docs)+";Volume :"+str(self.volume_docs)

class StatutTache(models.Model):
    id=models.AutoField(primary_key=True)
    statut=models.CharField(max_length=30)
    color=models.CharField(max_length=7,null=True,blank=True)
    
    def __str__(self):
        return self.statut
        
class Intervenant(models.Model):
    id=models.AutoField(primary_key=True)
    nom=models.CharField(max_length=150)
    prenom=models.CharField(max_length=75,null=True,blank=True)
    email=models.CharField(max_length=255,null=True,blank=True)
    tag=models.CharField(max_length=75,null=True,blank=True)
    notes=models.TextField(null=True,blank=True)

    def __str__(self):
        return self.nom+"-"+self.prenom
    
class Prestation(models.Model):
    id=models.AutoField(primary_key=True)
    projet=models.ForeignKey(Projet,on_delete=models.SET_NULL,null=True,blank=True)
    type_prestation=models.ForeignKey(TypePrestation,on_delete=models.SET_NULL,null=True,blank=True)
    intervenant=models.ForeignKey(Intervenant,on_delete=models.SET_NULL,null=True,blank=True)
    date_programmee=models.DateField(null=True,blank=True)
    date_realisation=models.DateField(null=True,blank=True)
    statut=models.ForeignKey(StatutTache,on_delete=models.SET_NULL,null=True, blank=True,default=1)
    notes=models.TextField(null=True,blank=True)
    
    def __str__(self):
        return self.projet.client.nom+"-"+self.type_prestation.type_prestation

class Tache(models.Model):
    id=models.AutoField(primary_key=True)
    projet=models.ForeignKey(Projet,on_delete=models.SET_NULL,null=True,blank=True)
    nom=models.CharField(max_length=150)
    date_programmee=models.DateField(null=True,blank=True)
    date_echeance=models.DateField(null=True,blank=True)
    date_realisation=models.DateField(null=True,blank=True)
    statut=models.ForeignKey(StatutTache,on_delete=models.SET_NULL,null=True,blank=True,default=1)
    temps_passe=models.CharField(max_length=20,null=True,blank=True)
    description=models.TextField(null=True,blank=True)
    intervenant=models.ManyToManyField(Intervenant,null=True,blank=True)
    
    def __str__(self):
        return self.nom+"-"+self.projet.client.nom


    
class Contact(models.Model):
    id=models.AutoField(primary_key=True)
    client=models.ForeignKey(Client,on_delete=models.SET_NULL,null=True,blank=True)
    type_projet=models.ForeignKey(TypeProjet,on_delete=models.SET_NULL,null=True,blank=True)
    nom=models.CharField(max_length=50)
    prenom=models.CharField(max_length=30,null=True,blank=True)
    email = models.EmailField(max_length=150,null=True,blank=True)
    tel = models.CharField(max_length=150,null=True,blank=True)
    notes=models.CharField(max_length=255,null=True,blank=True)
    
    def __str__(self):
        return str(self.nom)+" "+str(self.prenom)

class TypeEchange(models.Model):
    id=models.AutoField(primary_key=True)
    type_echange=models.CharField(max_length=50)
    
    def __str__(self):
        return self.type_echange
            
class Echange(models.Model):
    id=models.AutoField(primary_key=True)
    contact=models.ForeignKey(Contact,on_delete=models.SET_NULL,null=True,blank=True)
    projet=models.ForeignKey(Projet,on_delete=models.SET_NULL,null=True,blank=True)
    date=models.DateField(null=True,blank=True)
    heure=models.TimeField(null=True,blank=True)
    type_echange=models.ForeignKey(TypeEchange,on_delete=models.SET_NULL,null=True,blank=True)
    statut=models.ForeignKey(StatutTache,on_delete=models.SET_NULL,null=True,blank=True,default=1)
    temps_passe=models.CharField(max_length=20,null=True,blank=True,default="0")
    notes=models.TextField(null=True,blank=True)
    intervenant=models.ForeignKey(Intervenant, on_delete=models.SET_NULL,null=True,blank=True)
    
    def __str__(self):
        return self.type_echange.type_echange+"-"+str(self.contact.nom)+"-"+str(self.contact.prenom)

class TaskType(models.Model):
	id=models.AutoField(primary_key=True)
	type_task=models.CharField(max_length=150)
	tag=models.CharField(max_length=15,null=True,blank=True)
	color=models.CharField(max_length=8,null=True,blank=True)
	
	def __str__(self):
		return self.type_task
		
class Task(models.Model):
    id=models.AutoField(primary_key=True)
    projet=models.ForeignKey(Projet,on_delete=models.SET_NULL,null=True,blank=True)
    nom=models.CharField(max_length=150)
    task_type=models.ForeignKey(TaskType,on_delete=models.SET_NULL,null=True,blank=True)
    date_programmee=models.DateField(null=True,blank=True)
    heure=models.TimeField(null=True,blank=True)
    date_echeance=models.DateField(null=True,blank=True)
    date_realisation=models.DateField(null=True,blank=True)
    statut=models.ForeignKey(StatutTache,on_delete=models.SET_NULL,null=True,blank=True,default=1)
    temps_passe=models.CharField(max_length=20,null=True,blank=True)
    description=models.TextField(null=True,blank=True)
    intervenant=models.ManyToManyField(Intervenant,null=True,blank=True)
    contact=models.ForeignKey(Contact,on_delete=models.SET_NULL,null=True,blank=True)
    notes=models.TextField(null=True,blank=True)
    
    def __str__(self):
       return self.nom+"-"+self.projet.client.nom

app/suiviprojets/suiviprojets/dashboard/forms.py
#-*- coding:utf-8 -*-
import re
"""import floppyforms as forms"""
from django import forms
from django.forms import fields,widgets
from django.contrib import admin
from suiviprojets.dashboard.models import Task,Tache,Prestation,Echange,Contact,Projet,TaskType

class ProjetForm(forms.ModelForm):
	class Meta:
		model=Projet
		fields='__all__'

class TacheForm(forms.ModelForm):
	
	class Meta:
		model=Task
		fields=['projet','nom','date_programmee','date_echeance','date_realisation','statut','temps_passe','description','intervenant','notes']

class PrestationForm(forms.ModelForm):
	task_type=fields.CharField(widget=forms.HiddenInput(attrs={"value":1}),required=False)
	
	class Meta:
		model=Task
		fields=['projet','nom','date_programmee','date_echeance','date_realisation','statut','temps_passe','description','intervenant','notes']

class EchangeForm(forms.ModelForm):
	task_type=fields.CharField(widget=forms.HiddenInput(attrs={"value":3}),required=False)
	
	class Meta:
		model=Task
		fields=['projet','nom','date_programmee','heure','statut','temps_passe','description','intervenant','contact','notes']
		
class ContactForm(forms.ModelForm):
	email=forms.CharField(widget=forms.TextInput)
	class Meta:
		model=Contact
		fields='__all__'

app/suiviprojets/suiviprojets/templates/dashboard/current_tasks.html
<script>
	var resources = {{resources|safe}};
	var events = {{events|safe}}; 
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendarAll');
        var calendar = new FullCalendar.Calendar(calendarEl, {
          initialView: 'resourceTimelineMonth',
          aspectRatio:1,
          headerToolbar:{
			left:'prev,next',
			center:'title' 
		 },
		 
		 dayHeaderFormat:{ weekday: 'long', month: 'numeric', day: 'numeric', omitCommas: true },
		 slotLabelFormat: [
		  /*{ month: 'long', year: 'numeric' }, // top level of text*/
		  { weekday:'short'},
		  { day:'numeric' } // lower level of text
		],
		 editable:true,
		 resourceAreaHeaderContent:'Projets',
		 resourceAreaWidth:200,
		 resources:resources,
		 events:events,
		 eventMinWidth:100,
		 slotMinWidth:100,
		 eventContent:function(arg){
			let statut_marker=document.createElement("span");
			statut_marker.setAttribute("class","statut");
			statut_marker.setAttribute("style","background-color:#"+arg.event.extendedProps.statut+";");
			let content=document.createElement("p");
			content.setAttribute("title",arg.event.extendedProps.description);
			content.innerHTML=arg.event.title;
			let arrayofDomNodes=[statut_marker,content];
			return {domNodes:arrayofDomNodes};
																					
																				}
        });
        calendar.render();
      });

    </script>

    <div id='calendarAll'></div>

app/suiviprojets/suiviprojets/templates/dashboard/details.html
   
<!-- Page d'index -->
{% block content %}
<body>
<section id="global-content">
  	<div class="row main-title">
  		<div id="main-title" class="col-12 text-center">
  				<h2>D&eacute;tails du projet n°{{projet.num_armoire}} Client {{projet.client.nom}}</h2>
  		</div>
  	</div>
  	<div class="row">
		{% csrf_token %}
		<div class="col-2" id="resume">
			<h3>Résumé :</h3>
			<div id="resume">
				<p class="ligne"><label id="forfait" class="label">Forfait : </label><span>{{projet.forfait.categorie_forfait}}</span></p>
				<p class="ligne"><label id="date_commande" class="label">Date de commande : </label><span>{{projet.forfait.date_commande}}</span></p>
			</div>
		</div>
		<div class="col-5" id="contacts">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Contacts : </h3>
				</div>
				<div class="col-4 text-right">
					<a id="add-contact" data-objet="contact" class="btn btn-secondary" href='/admin/dashboard/contact/add/'>Ajouter contact</a>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<table id="contacts-table"class='table table-light table-striped'>
						<thead class="thead-light">
							<th>Nom</th>
							<th>Prénom</th>
							<th>@mail</th>
							<th>téléphones</th>
							<th>Edition</th>
						</thead>
						<tbody>
							{% for contact in projet.contacts %}
							<tr>
								<td class="contact-nom">{{contact.nom}}</td>
								<td class="contact-prenom">{{contact.prenom}}</td>
								<td class="contact-email">{{contact.email}}</td>
								<td class="contact-tel">{{contact.tel}}</td>
								<td class="contact-edit"><a id="edit" data-objet="contact" href='/admin/dashboard/contact/{{contact.id}}/change/'>Edit</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="col-5" id="echanges">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Echanges : </h3>
				</div>
				<div class="col-4 text-right">
					<a id="add-echange" data-objet="echange" class="btn btn-secondary" href='/admin/dashboard/echange/add/'>Ajouter échange</a>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<table id="contacts-table" class="table table-striped">
						<thead class="thead-light">
							<th>Date</th>
							<th>Contact</th>
							<th>Motif</th>
							<th>Edition</th>
						</thead>
						<tbody>
							{% for echange in projet.echanges %}
							<tr>
								<td class="echange-date">{{echange.date|date:'d/m/Y'}}</td>
								<td class="echange-contact">{{echange.contact}}</td>
								<td class="echange-type">{{echange.type_echange}}</td>
								<td><a id=""href='/admin/dashboard/echange/{{echange.id}}/change/'>Edit</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
  	</div>
  </div>
	<div class="row">
		<div class="col-6">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Prestations & D&eacute;veloppements Sp&eacute;cifiques :</h3>
				</div>
				<div class="col-4 text-right">
					<a class="btn btn-secondary" href='/admin/dashboard/prestation/add/'>Ajouter prestation</a>
				</div>
			</div>
			<div id="prestations">
				<table class='table table-striped'>
					<thead class="thead-light">
						<tr>
							<th>Type prestation</th>
							<th>Intervenant</th>
							<th>Date programmée</th>
							<th>statut</th>
							<th>Edition</th>
						</tr>
					</thead>
					<tbody>
						{% for pr in projet.prestations %}
						<tr>
							<td class="prestation-type">{{pr.type_prestation}}</td>
							<td class="prestation-intervenant">{{pr.intervenant}}</td>
							<td class="prestation-date">{{pr.date_programmee|date:"d/m/Y"}}</td>
							<td class="prestations-statut">{{pr.statut.statut}}</td>
							<td class="prestation-edit"><a href='/admin/dashboard/prestation/{{pr.id}}/change/'>Edit</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div><!--fin col-6-->
		<!-- autre colonne -->
	    <div class="col-6">
			<div class="row">
				<div class="col-9 text-left">
					<h3>Etat des tâches :</h3>
				</div>
				<!--<div class="col-1"></div>-->
				<div class="col-3 text-right">
					<a class="btn btn-secondary" href='/admin/dashboard/tache/add/'>Ajouter tâche</a>
				</div>
			</div>
			<div id="taches">
				<table class='table table-striped'>
					<thead class='thead-light'>
						<tr>
							<th>Nom</th>
							<th>Prévue le</th>
							<th>Echéance</th>
							<th >Statut</th>
							<th>Responsables</th>
							<!--<th>Description</th>-->
							<th>Edition</th>
						</tr>
					</thead>
					<tbody>
						{% for ta in projet.taches %}
						<tr>
							<td class="task-nom">{{ta.nom}}</td>
							<td class="tast-date">{{ta.date_programmee|date:"d/m/Y"}}</td>
							<td class="task-echeance">{{ta.date_echeance|date:"d/m/Y"}}</td>
							<td class="task-statut">{{pr.statut}}</td>
							<td class="task-presonne">{{ta.personne_en_charge}}</td>
							<!--<td class="task-description">{{ta.description}}</td>-->
							<td class="task-edit"><a href='/admin/dashboard/tache/{{ta.id}}/change/'>Edit</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
	    </div>
	</div><!-- fin row interne-->
	<div class="row">
		<div class="col-12">
			<script>
				var eventsct={{client.eventsct|safe|default:'[]'}};
				var eventscp={{client.eventscp|safe|default:'[]'}};
				var eventsce={{client.eventsce|safe|default:'[]'}};
			</script>
			<div id="calendar"></div>
		</div>
	</div>

		

  </body>
</section>
{% endblock %}

app/suiviprojets/suiviprojets/templates/dashboard/details_client.html
<!-- Page d'index -->
{% block content %}
<body>
<section id="global-content">
  	<div class="row main-title">
  		<div id="main-title" class="col-12 text-center">
  				<h2>D&eacute;tails du client {{client.nom}}</h2>
  		</div>
  	</div>
  	
  	<div class="row">
		<div class="col-5" id="resume">
			<h3>Adresse :</h3>
			<div id="resume">
				<p class="ligne"><h2>{{client.nom}}</h2></p>
				<p class="ligne"><h2>{{client.adresse1}}</h2></p>
				<p class="ligne"><h2>{{client.adresse2}}</h2></p>
				<p class="ligne"><h2>{{client.code_postal}}&nbsp;{{client.ville}}</h2></p>
			</div>
		</div>
		<div class="col-7" id="contacts">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Contacts : </h3>
				</div>
				<div class="col-4 text-right">
					<a class="btn btn-secondary" data-client="{{client.id}}" href='/admin/dashboard/contact/add/'>Ajouter contact</a>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<table id="contacts-table"class='table table-light table-striped'>
						<thead class="thead-light">
							<th>Nom</th>
							<th>Prénom</th>
							<th>@mail</th>
							<th>téléphones</th>
							<th>Edition</th>
						</thead>
						<tbody>
							{% for contact in client.contacts %}
							<tr>
								<td class="contact-nom">{{contact.nom}}</td>
								<td class="contact-prenom">{{contact.prenom}}</td>
								<td class="contact-email">{{contact.email}}</td>
								<td class="contact-tel">{{contact.tel}}</td>
								<td class="contact-edit"><a href='/admin/dashboard/contact/{{contact.id}}/change/'>Edit</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
				
	</div>
	<div class="row">
		<div class="col-12">
			<div class="row">
				<div class="col-12">
					<h3>D&eacute;tails des projets en cours</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<table class="table table-light table-striped">
						<thead class='thead-light'>
							<th>Type de projet</th>
							<th>Num&eacute;ro d'armoire</th>
							<th>Temps total pass&eacute;</th>
						</thead>
						<tbody>
							{% for projet in client.projets %}
							<tr>
								<td class="type_projet">{{projet.type_projet }}</td>
								<td class="numero_armoire">{% if projet.id == 1 %}{{ projet.num_armoire }}{% else %}/{% endif %}</td>
								<td class="temps_passe">{{projet.temps_passe}}</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
					<script>
						var eventsct={{client.eventsct|safe|default:'[]'}};
						var eventscp={{client.eventscp|safe|default:'[]'}};
						var eventsce={{client.eventsce|safe|default:'[]'}};
					</script>
					<div id="calendar"></div>
		</div>
	</div>
</section>
</body>
{% endblock %}

app/suiviprojets/suiviprojets/templates/dashboard/details_projet -archive.html
   
<!-- Page d'index -->
{% block content %}
<body>
<section id="global-content">
  	<div class="row main-title">
  		<div id="main-title" class="col-12 text-center">
  				<h2>D&eacute;tails du projet n°{{projet.num_armoire}} Client {{projet.client.nom}}</h2>
  				<input type="hidden" id="id_projet" value="{{projet.id}}">
  				<input type="hidden" id="id_type_projet" value="{{projet.type_projet.id}}">
  				<input type="hidden" id="id_client" value="{{projet.client.id}}">
  		</div>
  	</div>
  	<div class="row">
		{% csrf_token %}
		<div class="col-2" id="resume">
			<h3>Résumé :</h3>
			<div id="resume">
				<p class="ligne"><label id="type_projet">Type de projet : </label><span>{{projet.type_projet.type_projet}}</span></p>
				<p class="ligne"><label id="forfait" class="label">Forfait : </label><span>{{projet.forfait.categorie_forfait}}</span></p>
				<p class="ligne"><label id="date_commande" class="label">Date de commande : </label><span>{{projet.forfait.date_commande}}</span></p>
			</div>
		</div>
		<div class="col-5" id="contacts">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Contacts : </h3>
				</div>
				<div class="col-4 text-right">
					<a id="add-contact" data-client="{{projet.client.id}}" data-type_projet="{{projet.type_projet.id}}" data-projet="{{projet.id}}" data-objet="contact" class="btn btn-secondary" href='/admin/dashboard/contact/add/'>Ajouter contact</a>
				</div>
			</div>
			<div class="row">
				<div class="col-12 partiel_contacts">
					{% include 'partiel_contact.html' %}
				</div>
			</div>
		</div>
		<div class="col-5" id="echanges">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Echanges : </h3>
				</div>
				<div class="col-4 text-right">
					<a id="add-echange" data-projet="{{projet.id}}" data-objet="echange" class="btn btn-secondary" href='/admin/dashboard/echange/add/'>Ajouter échange</a>
				</div>
			</div>
			<div class="row">
				<div class="col-12 partiel_echanges">
					{% include 'partiel_echange.html' %}
				</div>
			</div>
  	</div>
  </div>
	<div class="row">
		<div class="col-6">
			<div class="row">
				<div class="col-8 text-left">
					<h3>Prestations & D&eacute;veloppements Sp&eacute;cifiques :</h3>
				</div>
				<div class="col-4 text-right">
					<a id="add-prestation" class="btn btn-secondary" data-projet="{{projet.id}}" data-objet="prestation" href='/admin/dashboard/prestation/add/'>Ajouter prestation</a>
				</div>
			</div>
			<div id="prestations" class="partiel_prestation">
				{% include 'partiel_prestation.html' %}
			</div>
		</div><!--fin col-6-->
		<!-- autre colonne -->
	    <div class="col-6">
			<div class="row">
				<div class="col-9 text-left">
					<h3>Etat des tâches :</h3>
				</div>
				<!--<div class="col-1"></div>-->
				<div class="col-3 text-right">
					<a id="add-tache" class="btn btn-secondary" data-projet="{{projet.id}}" data-objet="tache" href='/admin/dashboard/tache/add/'>Ajouter tâche</a>
				</div>
			</div>
			<div id="taches" class="partiel_taches">
				{% include 'partiel_tache.html' %}
			</div>
	    </div>
	</div><!-- fin row interne-->
	<div class="row">
		<div class="col-12">
			<script>
				var eventsct={{client.eventsct|safe|default:'[]'}};
				var eventscp={{client.eventscp|safe|default:'[]'}};
				var eventsce={{client.eventsce|safe|default:'[]'}};
			</script>
			<div id="calendar"></div>
		</div>
	</div>

		

  </body>
</section>
{% endblock %}

app/suiviprojets/suiviprojets/templates/dashboard/filtre.html
<div class="row">
    <div class="col-10">
        <div class="filtre filtre-line-1 row">
            <div id="line-1-bloc-1" class="col-3">
                    <div class="d-wrapper">
						<div class="control-label label-info ">Numéro d'armoire :</div>

                            <div class="col-12 input-group">        
                                <input id="num_armoire" class="keyup form-control" type="text" name="num_armoire" value="" placeholder="Numéro d'armoire"/>
                            </div>
                        
                    </div>
            </div>
             <div id="line-1-bloc-2" class="col-3">
                <div class="d-wrapper">
                    <div class="control-label label-info">Client : </div>
	                    <div class="col-12 input-group">
	                            <input id="nom" type="text" class="keyup form-control" name="nom" value="" placeholder="client"/>
	                     </div>
                </div>

            </div>
            <div id="line-1-bloc-3" class="col-3">
				<div class="control-label label-info">Forfaits : </div>
                    <select id="forfait" name="forfait" class="change form-control" multiple="multiple" >
                            {% for forfait in filtres.forfaits %}
                                <option value="{{forfait.id}}">{{forfait.type_forfait}}</option>
                            {% endfor %}
                    </select>
                </div>
            </div>
            <div id="line-1-bloc-3" class="col-1">
		     </div><!--separateur-->

        </div>
        
		

    
    <div class="col-2">
        <div class="filtre btn-group-vertical">
            <input id="search" class="btn" type="button" name="search" value="Rechercher"/>
            <form id="download-form" action="/download/" method="POST">
                    {% csrf_token %}
                    <input id="download-button" class="download btn btn-success" type="submit" name="download" value="T&eacute;l&eacute;charger"/>
            </form>
        </div><!-- /group-vertical -->
    </div>
</div>

app/suiviprojets/suiviprojets/templates/dashboard/partiel_contact.html
	<table id="contacts-table"class='table table-light table-striped'>
		<thead class="thead-light">
			<th>Nom</th>
			<th>Prénom</th>
			<th>@mail</th>
			<th>téléphones</th>
			<th>Edition</th>
		</thead>
		<tbody>
			{% for contact in projet.contacts %}
			<tr>
				<td class="contact-nom">{{contact.nom}}</td>
				<td class="contact-prenom">{{contact.prenom}}</td>
				<td class="contact-email">{{contact.email}}</td>
				<td class="contact-tel">{{contact.tel}}</td>
				<td class="contact-edit"><a id="contact-{{contact.id}}-edit" class="edit" data-objet="contact" data-projet="{{projet.id}}" data-id="{{contact.id}}" href='/admin/dashboard/contact/{{contact.id}}/change/'>Edit</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>